/*
 * SoloDungeonQuests.h - the dungeon -> quest map used by the GM Toolkit's "Dungeon quests" menu.
 *
 * Rows come from the world table solo_dungeon_quests (generated by tools/build_dungeon_quests.py, applied by
 * sql/world/mod-solo-dungeon-quests.sql). Loaded at startup and again on `.reload config`.
 */
#pragma once

#include "Define.h"

#include <string>
#include <vector>

class Player;

struct SoloDungeon
{
    uint32 map;
    std::string name;
    std::string expansion;
    uint32 level;                  // suggested level, for the label
    std::vector<uint32> quests;    // quest ids, low level first
};

std::vector<SoloDungeon> const& SoloDungeonList();
std::vector<std::string> const& SoloDungeonExpansions();   // in table order (Classic, Burning Crusade, Wrath)
SoloDungeon const* SoloDungeonForMap(uint32 map);

// adds every quest of the dungeon the player can hold; returns a one-line summary for chat
std::string SoloGrantDungeonQuests(Player* p, SoloDungeon const& d);
