-- mod-solo: restore class restrictions on tier/set gear (generated by tools/fix_gear_allowable_class.py)
-- Fixes cross-class tier gear on bots (classless CoA item data). Idempotent; item_template is boot-cached so effective after a worldserver restart.
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22416 AND `AllowableClass`=1535; -- Dreadnaught Breastplate
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22417 AND `AllowableClass`=1535; -- Dreadnaught Legplates
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22418 AND `AllowableClass`=1535; -- Dreadnaught Helmet
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22419 AND `AllowableClass`=1535; -- Dreadnaught Pauldrons
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22420 AND `AllowableClass`=1535; -- Dreadnaught Sabatons
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22421 AND `AllowableClass`=1535; -- Dreadnaught Gauntlets
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22422 AND `AllowableClass`=1535; -- Dreadnaught Waistguard
UPDATE `item_template` SET `AllowableClass`=1 WHERE `entry`=22423 AND `AllowableClass`=1535; -- Dreadnaught Bracers
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22424 AND `AllowableClass`=32767; -- Redemption Wristguards
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22425 AND `AllowableClass`=32767; -- Redemption Tunic
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22426 AND `AllowableClass`=32767; -- Redemption Handguards
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22427 AND `AllowableClass`=32767; -- Redemption Legguards
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22428 AND `AllowableClass`=32767; -- Redemption Headpiece
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22429 AND `AllowableClass`=32767; -- Redemption Spaulders
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22430 AND `AllowableClass`=32767; -- Redemption Boots
UPDATE `item_template` SET `AllowableClass`=2 WHERE `entry`=22431 AND `AllowableClass`=32767; -- Redemption Girdle
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22436 AND `AllowableClass`=32767; -- Cryptstalker Tunic
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22437 AND `AllowableClass`=32767; -- Cryptstalker Legguards
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22438 AND `AllowableClass`=32767; -- Cryptstalker Headpiece
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22439 AND `AllowableClass`=32767; -- Cryptstalker Spaulders
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22440 AND `AllowableClass`=32767; -- Cryptstalker Boots
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22441 AND `AllowableClass`=32767; -- Cryptstalker Handguards
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22442 AND `AllowableClass`=32767; -- Cryptstalker Girdle
UPDATE `item_template` SET `AllowableClass`=4 WHERE `entry`=22443 AND `AllowableClass`=32767; -- Cryptstalker Wristguards
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22464 AND `AllowableClass`=32767; -- Earthshatter Tunic
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22465 AND `AllowableClass`=32767; -- Earthshatter Legguards
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22466 AND `AllowableClass`=32767; -- Earthshatter Headpiece
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22467 AND `AllowableClass`=32767; -- Earthshatter Spaulders
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22468 AND `AllowableClass`=32767; -- Earthshatter Boots
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22469 AND `AllowableClass`=32767; -- Earthshatter Handguards
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22470 AND `AllowableClass`=32767; -- Earthshatter Girdle
UPDATE `item_template` SET `AllowableClass`=64 WHERE `entry`=22471 AND `AllowableClass`=32767; -- Earthshatter Wristguards
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22476 AND `AllowableClass`=1535; -- Bonescythe Breastplate
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22477 AND `AllowableClass`=32767; -- Bonescythe Legplates
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22478 AND `AllowableClass`=1535; -- Bonescythe Helmet
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22479 AND `AllowableClass`=1535; -- Bonescythe Pauldrons
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22480 AND `AllowableClass`=32767; -- Bonescythe Sabatons
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22481 AND `AllowableClass`=1535; -- Bonescythe Gauntlets
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22482 AND `AllowableClass`=1535; -- Bonescythe Waistguard
UPDATE `item_template` SET `AllowableClass`=8 WHERE `entry`=22483 AND `AllowableClass`=1535; -- Bonescythe Bracers
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22488 AND `AllowableClass`=32767; -- Dreamwalker Tunic
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22489 AND `AllowableClass`=32767; -- Dreamwalker Legguards
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22490 AND `AllowableClass`=32767; -- Dreamwalker Headpiece
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22491 AND `AllowableClass`=32767; -- Dreamwalker Spaulders
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22492 AND `AllowableClass`=32767; -- Dreamwalker Boots
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22493 AND `AllowableClass`=32767; -- Dreamwalker Handguards
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22494 AND `AllowableClass`=32767; -- Dreamwalker Girdle
UPDATE `item_template` SET `AllowableClass`=1024 WHERE `entry`=22495 AND `AllowableClass`=32767; -- Dreamwalker Wristguards
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22496 AND `AllowableClass`=32767; -- Frostfire Robe
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22497 AND `AllowableClass`=32767; -- Frostfire Leggings
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22498 AND `AllowableClass`=32767; -- Frostfire Circlet
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22499 AND `AllowableClass`=32767; -- Frostfire Shoulderpads
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22500 AND `AllowableClass`=32767; -- Frostfire Sandals
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22501 AND `AllowableClass`=32767; -- Frostfire Gloves
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22502 AND `AllowableClass`=32767; -- Frostfire Belt
UPDATE `item_template` SET `AllowableClass`=128 WHERE `entry`=22503 AND `AllowableClass`=32767; -- Frostfire Bindings
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22504 AND `AllowableClass`=32767; -- Plagueheart Robe
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22505 AND `AllowableClass`=32767; -- Plagueheart Leggings
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22506 AND `AllowableClass`=32767; -- Plagueheart Circlet
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22507 AND `AllowableClass`=32767; -- Plagueheart Shoulderpads
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22508 AND `AllowableClass`=32767; -- Plagueheart Sandals
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22509 AND `AllowableClass`=32767; -- Plagueheart Gloves
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22510 AND `AllowableClass`=32767; -- Plagueheart Belt
UPDATE `item_template` SET `AllowableClass`=256 WHERE `entry`=22511 AND `AllowableClass`=32767; -- Plagueheart Bindings
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22512 AND `AllowableClass`=32767; -- Robe of Faith
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22513 AND `AllowableClass`=32767; -- Leggings of Faith
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22514 AND `AllowableClass`=32767; -- Circlet of Faith
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22515 AND `AllowableClass`=32767; -- Shoulderpads of Faith
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22516 AND `AllowableClass`=32767; -- Sandals of Faith
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22517 AND `AllowableClass`=32767; -- Gloves of Faith
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22518 AND `AllowableClass`=32767; -- Belt of Faith
UPDATE `item_template` SET `AllowableClass`=16 WHERE `entry`=22519 AND `AllowableClass`=32767; -- Bindings of Faith
UPDATE `item_template` SET `AllowableClass`=32 WHERE `entry`=48890 AND `AllowableClass`=262143; -- Koltira's Chestguard 
UPDATE `item_template` SET `AllowableClass`=32 WHERE `entry`=48894 AND `AllowableClass`=262143; -- Koltira's Pauldrons 
UPDATE `item_template` SET `AllowableClass`=32 WHERE `entry`=48895 AND `AllowableClass`=262143; -- Thassarian's Chestguard 
UPDATE `item_template` SET `AllowableClass`=32 WHERE `entry`=48899 AND `AllowableClass`=262143; -- Thassarian's Pauldrons 
