#!/usr/bin/env python3
"""Turn server/personalities/personalities.txt (plain text, edit it in Notepad) into the SQL pack the server uses,
apply it to the running database, and tell the bots to reload.

usage: build_personalities.py            build + apply + reload
       build_personalities.py --reroll   same, and also wipe every bot's current assignment so all bots re-roll a
                                         personality from the new list the next time they speak
       build_personalities.py --check    just parse and report, change nothing

File format (personalities.txt):
    === KEY ===            starts a personality; KEY = letters, digits, underscores (shown in .ollama personality list)
    the lines that follow, until the next === KEY ===, are the profile text given to the model
    # lines starting with # are comments and are ignored
Bots pick a personality at random, uniformly, from every entry in the file. So the MIX is the COUNT: ten toxic entries,
six normal, four nice = 50/30/20. Want more of one kind? Add entries (variants of the same type are fine).
"""
import json, os, re, subprocess, sys, urllib.request, urllib.error, base64, html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SERVER = os.path.join(ROOT, "server")
SRC = os.path.join(SERVER, "personalities", "personalities.txt")
OUT = os.path.join(SERVER, "personalities", "2026_09_06_00_personality_pack_genchat.sql")
EXAMPLE = os.path.join(SERVER, "personalities", "personalities.example.txt")

# personalities.txt is yours and stays out of git (so is the SQL built from it); a fresh clone starts from the example.
if not os.path.exists(SRC) and os.path.exists(EXAMPLE):
    import shutil
    shutil.copy(EXAMPLE, SRC)
    print("personalities.txt created from personalities.example.txt - edit it, it is not versioned")


def settings():
    s = json.load(open(os.path.join(SERVER, "settings.json"), encoding="utf-8-sig"))
    local = os.path.join(SERVER, "settings.local.json")
    if os.path.exists(local):
        s.update(json.load(open(local, encoding="utf-8")))
    return s


def parse(path):
    entries, key, buf = [], None, []
    for raw in open(path, encoding="utf-8-sig"):
        line = raw.rstrip("\n")
        m = re.match(r"^===\s*([A-Za-z0-9_]+)\s*===\s*$", line)
        if m:
            if key:
                entries.append((key, " ".join(x.strip() for x in buf if x.strip())))
            key, buf = m.group(1).upper(), []
            continue
        if line.lstrip().startswith("#"):
            continue
        if key:
            buf.append(line)
    if key:
        entries.append((key, " ".join(x.strip() for x in buf if x.strip())))
    problems = [k for k, t in entries if not t]
    if problems:
        sys.exit("these personalities have no text: " + ", ".join(problems))
    keys = [k for k, _ in entries]
    dupes = sorted({k for k in keys if keys.count(k) > 1})
    if dupes:
        sys.exit("duplicate keys (each === KEY === must be unique): " + ", ".join(dupes))
    if not entries:
        sys.exit("no personalities found in " + path)
    return entries


def sql_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def build_sql(entries):
    lines = [
        "-- GENERATED by tools/build_personalities.py from server/personalities/personalities.txt - edit THAT file, not this one.",
        "-- Bots pick uniformly at random from every row with manual_only = 0, so the number of entries per kind is the mix.",
        "-- The 33 templates that ship with mod-ollama-chat are switched to manual_only (usable via .ollama personality set).",
        "INSERT INTO `mod_ollama_chat_personality_templates` (`key`, `prompt`, `manual_only`) VALUES",
    ]
    lines.append(",\n".join("(%s, %s, 0)" % (sql_str(k), sql_str(t)) for k, t in entries))
    lines.append("AS new ON DUPLICATE KEY UPDATE `prompt` = new.`prompt`, `manual_only` = new.`manual_only`;")
    keys = ", ".join(sql_str(k) for k, _ in entries)
    # anything not in the file is parked (stock templates and personalities you deleted from the file)
    lines.append("UPDATE `mod_ollama_chat_personality_templates` SET `manual_only` = 1 WHERE `key` NOT IN (%s);" % keys)
    return "\n".join(lines) + "\n"


def mysql(S, db, sql):
    exe = os.path.join(SERVER, "mysql", "mysql-8.4.0-winx64", "bin", "mysql.exe")
    env = dict(os.environ, MYSQL_PWD=S["DbPassword"])
    r = subprocess.run([exe, "--user=" + S["DbUser"], "--host=127.0.0.1", "--port=%s" % S["MySQLPort"],
                        "--database=%s_%s" % (S["DbPrefix"], db), "--batch"], input=sql, text=True, env=env,
                       capture_output=True, encoding="utf-8")
    if r.returncode != 0:
        sys.exit("mysql failed: " + r.stderr.strip())
    return r.stdout


def soap(S, command):
    body = f'''<?xml version="1.0" encoding="utf-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:AC">
 <SOAP-ENV:Body><ns1:executeCommand><command>{html.escape(command)}</command></ns1:executeCommand></SOAP-ENV:Body>
</SOAP-ENV:Envelope>'''.encode()
    req = urllib.request.Request(f'http://127.0.0.1:{S["SoapPort"]}/', data=body, method='POST')
    req.add_header('Content-Type', 'application/xml')
    req.add_header('Authorization', 'Basic ' + base64.b64encode(f'{S["Account"]}:{S["Password"]}'.encode()).decode())
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            return r.read().decode("utf-8", "replace")
    except (urllib.error.URLError, OSError):
        return None


def main():
    S = settings()
    entries = parse(SRC)
    print("personalities.txt: %d personalities: %s" % (len(entries), ", ".join(k for k, _ in entries)))
    if "--check" in sys.argv:
        return
    sql = build_sql(entries)
    open(OUT, "w", encoding="utf-8").write(sql)
    print("wrote", os.path.relpath(OUT, ROOT))
    # keep the copy the server auto-applies on boot in step too
    mod = os.path.join(SERVER, "azerothcore", "modules", "mod-ollama-chat", "data", "sql", "characters", "updates")
    if os.path.isdir(mod):
        open(os.path.join(mod, os.path.basename(OUT)), "w", encoding="utf-8").write(sql)
    try:
        mysql(S, "characters", sql)
        if "--reroll" in sys.argv:
            mysql(S, "characters", "DELETE FROM `mod_ollama_chat_personality`;")
            print("cleared every bot's assignment - they re-roll from the new list the next time they speak")
        out = mysql(S, "characters", "SELECT COUNT(*) FROM `mod_ollama_chat_personality_templates` WHERE manual_only = 0;")
        print("database: %s personalities active" % out.split()[-1])
    except SystemExit as e:
        print(str(e))
        print("(is MySQL running?  solo.cmd mysql)  The file is saved; the server applies it on its next start.")
        return
    r = soap(S, "ollama reload")
    print("bots reloaded" if r and "reload" in r.lower() else "server not running - the new personalities load on the next start")


if __name__ == "__main__":
    main()
