#!/usr/bin/env python3
"""Regenerate server/modules/mod-solo/sql/world/mod-solo-gear-class-fix.sql.

Why: this world DB inherited classless (Ascension/CoA) item data, so class tier/set
armor is flagged usable by every class (AllowableClass = 1535 / 32767 / -1). The bot
gear factory then legitimately equips e.g. rogue T3 (Bonescythe) on a hunter or mage T3
(Frostfire) on a priest, because the DB says any class may wear it.

There is no correct stock reference locally (the base item_template.sql is itself the
classless CoA merge). But most tier sets exist in several versions across expansions and
at least one version is correctly restricted to a single class (e.g. vanilla "Bonescythe
Breastplate" = 1535 but "Valorous Bonescythe Breastplate" = 8 = rogue). We recover the
right class by grouping set pieces by their base set-name + slot and copying the correct
single-class mask onto the broken siblings.

Scope: only items that belong to an itemset (tier/set gear) and whose class is resolvable
this way. Generic non-set gear (correctly all-class in stock) is left untouched, as are
Ascension custom items (no restricted sibling to learn from). Output is idempotent
(plain UPDATEs keyed by entry) and runs at solo.cmd configs / start; item_template is
boot-cached so it takes effect at the next worldserver restart.
"""
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MYSQL = ROOT / "server/mysql/mysql-8.4.0-winx64/bin/mysql.exe"
OUT = ROOT / "server/modules/mod-solo/sql/world/mod-solo-gear-class-fix.sql"

# tier / set name prefixes to strip so the vanilla and reprinted versions of a set collapse
# to the same base key (order-independent; applied repeatedly)
PREFIXES = [
    "heroes'", "valorous", "conqueror's", "triumphant", "sanctified", "gladiator's",
    "merciless gladiator's", "vengeful gladiator's", "brutal gladiator's",
    "deadly gladiator's", "furious gladiator's", "relentless gladiator's",
    "wrathful gladiator's", "hateful gladiator's", "savage gladiator's",
]

POPULAR_ARMOR_SLOTS = {1, 3, 5, 6, 7, 8, 9, 10, 20}  # head/shoulder/chest/waist/legs/feet/wrist/hands/robe


def popcount(mask):
    return bin(mask & 0x7FF).count("1")  # classes 1..11


def is_single_class(mask):
    return mask > 0 and popcount(mask) == 1


def base_key(name):
    n = name.strip().lower()
    changed = True
    while changed:
        changed = False
        for p in PREFIXES:
            if n.startswith(p + " "):
                n = n[len(p) + 1:]
                changed = True
    return n


def run_query(sql):
    r = subprocess.run(
        [str(MYSQL), "--host=127.0.0.1", "--port=3307", "--user=acore",
         "--password=acore", "-N", "-e", sql],
        capture_output=True, text=True,
    )
    lines = [l for l in r.stdout.splitlines() if l and "Using a password" not in l]
    return [l.split("\t") for l in lines]


def main():
    # every armor/weapon item that belongs to a set (tier/set gear is the class-identifiable set)
    rows = run_query(
        "SELECT entry, name, AllowableClass, itemset, InventoryType "
        "FROM acore_world.item_template "
        "WHERE itemset<>0 AND class IN (2,4);"
    )
    items = []
    for entry, name, allow, itemset, inv in rows:
        items.append((int(entry), name, int(allow), int(itemset), int(inv)))

    # learn the correct single-class mask per (base set name, slot) and per itemset
    by_namekey = defaultdict(set)   # (base_name, inv) -> {single-class masks}
    by_itemset = defaultdict(set)   # itemset -> {single-class masks}
    for entry, name, allow, itemset, inv in items:
        if is_single_class(allow):
            by_namekey[(base_key(name), inv)].add(allow)
            by_itemset[itemset].add(allow)

    fixes = []       # (entry, old, new, name)
    unresolved = []  # (entry, name, itemset)
    for entry, name, allow, itemset, inv in items:
        if is_single_class(allow):
            continue  # already correct
        # candidate correct masks: prefer same-slot namesake, then same itemset
        cand = by_namekey.get((base_key(name), inv), set())
        if not cand:
            cand = by_itemset.get(itemset, set())
        if len(cand) == 1:
            new = next(iter(cand))
            if new != allow:
                fixes.append((entry, allow, new, name))
        else:
            unresolved.append((entry, name, itemset))

    fixes.sort()
    header = (
        "-- mod-solo: restore class restrictions on tier/set gear (generated by "
        "tools/fix_gear_allowable_class.py)\n"
        "-- Fixes cross-class tier gear on bots (classless CoA item data). Idempotent; "
        "item_template is boot-cached so effective after a worldserver restart.\n"
    )
    with open(OUT, "w", newline="\n") as f:
        f.write(header)
        for entry, old, new, name in fixes:
            f.write(
                f"UPDATE `item_template` SET `AllowableClass`={new} WHERE `entry`={entry} "
                f"AND `AllowableClass`={old}; -- {name}\n"
            )

    print(f"set items scanned: {len(items)}")
    print(f"already single-class: {sum(1 for i in items if is_single_class(i[2]))}")
    print(f"FIXED (resolved to one class): {len(fixes)}")
    print(f"unresolved (ambiguous/no restricted sibling): {len(unresolved)}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    if unresolved and "-v" in sys.argv:
        print("\n-- sample unresolved --")
        for entry, name, itemset in unresolved[:40]:
            print(f"  {entry}\t{name}\t(set {itemset})")


if __name__ == "__main__":
    main()
