#!/usr/bin/env python3
"""Worldforged gear as world drops.

Reads an item_template dump (the CoA project's coa_items.sql, itself built from the Ascension client's item cache),
keeps every item whose description carries the @Worldforged@ tag, and writes two SQL files into server/local (which
is git-ignored: this is Ascension's data, and the item ids only render on an Ascension-copy client):

  worldforged-items.sql   INSERT IGNORE of the items (tag stripped from the description)
  worldforged-loot.sql    one reference loot table per level band, attached to every lootable creature of that band

Band = the creature's level range. An item joins the band of its RequiredLevel (below 60) or, for the level-60+ set,
of its ItemLevel, so Outland and Northrend mobs drop the endgame pieces. Every creature in a band gets one extra
loot line pointing at the band's table; the chance depends on the creature's rank.

usage: worldforged_loot.py <coa_items.sql> [--apply]
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SERVER = os.path.join(ROOT, "server")
LOCAL = os.path.join(SERVER, "local")
MYSQL = os.path.join(SERVER, "mysql", "mysql-8.4.0-winx64", "bin", "mysql.exe")

REF_BASE = 9200001          # reference_loot_template entries we own
CHANCE = {0: 1.0, 1: 4.0, 2: 20.0, 3: 100.0, 4: 20.0}   # creature rank -> % chance of one Worldforged drop

# creature level bands: (min, max) -> index
BANDS = [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30), (31, 35), (36, 40), (41, 45), (46, 50), (51, 55),
         (56, 60), (61, 65), (66, 70), (71, 75), (76, 80), (81, 83)]




def band_for_creature(level):
    for i, (lo, hi) in enumerate(BANDS):
        if lo <= level <= hi:
            return i
    return None


def settings():
    import json
    s = json.load(open(os.path.join(SERVER, "settings.json"), encoding="utf-8-sig"))
    p = os.path.join(SERVER, "settings.local.json")
    if os.path.exists(p):
        s.update(json.load(open(p, encoding="utf-8-sig")))
    return s


def mysql(S, db, sql):
    env = dict(os.environ, MYSQL_PWD=S["DbPassword"])
    r = subprocess.run([MYSQL, "-N", "--user=%s" % S["DbUser"], "--host=127.0.0.1", "--port=%s" % S["MySQLPort"],
                        "--database=%s_%s" % (S["DbPrefix"], db), "-e", sql], capture_output=True, text=True, env=env)
    if r.returncode:
        sys.exit(r.stderr)
    return [line.split("\t") for line in r.stdout.splitlines() if line]


def mysql_file(S, db, path):
    env = dict(os.environ, MYSQL_PWD=S["DbPassword"])
    with open(path, "rb") as f:
        r = subprocess.run([MYSQL, "--user=%s" % S["DbUser"], "--host=127.0.0.1", "--port=%s" % S["MySQLPort"],
                            "--database=%s_%s" % (S["DbPrefix"], db)], stdin=f, capture_output=True, text=True, env=env)
    if r.returncode:
        sys.exit(r.stderr)


SPLIT = re.compile(r",(?=(?:[^']*'[^']*')*[^']*$)")


def parse_dump(path):
    cols, rows = None, []
    for line in open(path, encoding="utf-8", errors="replace"):
        if cols is None and line.startswith("REPLACE INTO"):
            cols = re.findall(r"`([^`]+)`", line.split("(", 1)[1].split(")", 1)[0])
            continue
        if "@Worldforged@" not in line:
            continue
        s = line.strip()
        if not s.startswith("("):
            continue
        s = s[1:].rstrip(",;")
        if s.endswith(")"):
            s = s[:-1]
        parts = SPLIT.split(s)
        if len(parts) != len(cols):
            continue
        rows.append(parts)
    return cols, rows


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    dump = sys.argv[1]
    apply = "--apply" in sys.argv
    S = settings()
    cols, rows = parse_dump(dump)
    idx = {c: i for i, c in enumerate(cols)}
    have = {c[0] for c in mysql(S, "world", "SHOW COLUMNS FROM item_template")}
    missing = [c for c in cols if c not in have]
    if missing:
        sys.exit("dump columns not in this core's item_template: %s" % missing)
    print("worldforged items in dump: %d" % len(rows))

    os.makedirs(LOCAL, exist_ok=True)
    items_sql = os.path.join(LOCAL, "worldforged-items.sql")
    with open(items_sql, "w", encoding="utf-8") as f:
        f.write("-- generated by tools/worldforged_loot.py: Worldforged items from the Ascension item cache. INSERT IGNORE = idempotent.\n")
        f.write("SET NAMES utf8mb4;\n")
        for i in range(0, len(rows), 400):
            chunk = rows[i:i + 400]
            f.write("INSERT IGNORE INTO item_template (%s) VALUES\n" % ",".join("`%s`" % c for c in cols))
            out = []
            for r in chunk:
                r = list(r)
                r[idx["description"]] = r[idx["description"]].replace("@Worldforged@", "")
                out.append("(" + ",".join(r) + ")")
            f.write(",\n".join(out) + ";\n")

    # bands. Below 60 an item follows its RequiredLevel. The 60+ set (Ascension caps at 60, so its item levels only
    # run to ~90) is spread by item level, in equal shares, over the six bands from 56 to 83: the best of it drops
    # in Northrend, the weakest in the Plaguelands.
    per_band = {i: [] for i in range(len(BANDS))}
    endgame = []
    for r in rows:
        req, il, entry = int(r[idx["RequiredLevel"]]), int(r[idx["ItemLevel"]]), int(r[idx["entry"]])
        if req < 60:
            per_band[min(11, max(0, (req - 1) // 5))].append(entry)
        else:
            endgame.append((il, entry))
    endgame.sort()
    top_bands = list(range(11, len(BANDS)))
    share = (len(endgame) + len(top_bands) - 1) // len(top_bands)
    for j, b in enumerate(top_bands):
        per_band[b].extend(e for _, e in endgame[j * share:(j + 1) * share])
    creatures = mysql(S, "world", "SELECT lootid, minlevel, `rank` FROM creature_template WHERE lootid > 0 AND type <> 8 AND npcflag = 0 AND minlevel BETWEEN 1 AND 83")
    by_loot = {}
    for lootid, lvl, rank in creatures:
        b = band_for_creature(int(lvl))
        if b is not None and int(lootid) not in by_loot:
            by_loot[int(lootid)] = (b, int(rank))

    loot_sql = os.path.join(LOCAL, "worldforged-loot.sql")
    refs = ",".join(str(REF_BASE + i) for i in range(len(BANDS)))
    with open(loot_sql, "w", encoding="utf-8") as f:
        f.write("-- generated by tools/worldforged_loot.py: one Worldforged drop table per creature level band. Idempotent.\n")
        f.write("DELETE FROM reference_loot_template WHERE Entry IN (%s);\n" % refs)
        f.write("DELETE FROM creature_loot_template WHERE Reference IN (%s);\n" % refs)
        for i, (lo, hi) in enumerate(BANDS):
            items = per_band[i]
            if not items:
                continue
            f.write("INSERT INTO reference_loot_template (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment) VALUES\n")
            f.write(",\n".join("(%d, %d, 0, 0, 0, 1, 1, 1, 1, 'worldforged %d-%d')" % (REF_BASE + i, it, lo, hi) for it in items) + ";\n")
        lines = []
        for lootid, (b, rank) in sorted(by_loot.items()):
            if not per_band[b]:
                continue
            lines.append("(%d, %d, %d, %.1f, 0, 1, 0, 1, 1, 'worldforged')" % (lootid, REF_BASE + b, REF_BASE + b, CHANCE.get(rank, 1.0)))
        for i in range(0, len(lines), 1000):
            f.write("INSERT IGNORE INTO creature_loot_template (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment) VALUES\n")
            f.write(",\n".join(lines[i:i + 1000]) + ";\n")

    for i, (lo, hi) in enumerate(BANDS):
        n_c = sum(1 for b, _ in by_loot.values() if b == i)
        print("  band %2d-%2d: %5d items, %5d creature loot tables" % (lo, hi, len(per_band[i]), n_c))
    print("wrote", items_sql, "and", loot_sql)

    if apply:
        mysql_file(S, "world", items_sql)
        mysql_file(S, "world", loot_sql)
        n = mysql(S, "world", "SELECT COUNT(*) FROM item_template WHERE entry IN (%s)" % ",".join(str(int(r[idx["entry"]])) for r in rows[:2000]))
        print("applied. sample check: %s of the first 2000 items present" % n[0][0])


if __name__ == "__main__":
    main()
